export const VERIFY_BVN_SUCCESS = 'VERIFY_BVN_SUCCESS';
export const VERIFY_BVN_ERROR = 'VERIFY_BVN_ERROR';

export const PERSONAL_DETAILS_SUCCESS = 'PERSONAL_DETAILS_SUCCESS';
export const PERSONAL_DETAILS_ERROR = 'PERSONAL_DETAILS_ERROR';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_ERROR = 'FETCH_ORGANIZATIONS_ERROR';

export const FETCH_ORGANIZATIONS_BY_NAME_SUCCESS = 'FETCH_ORGANIZATIONS_BY_NAME_SUCCESS';
export const FETCH_ORGANIZATIONS_BY_NAME_ERROR = 'FETCH_ORGANIZATIONS_BY_NAME_ERROR';

export const GENDER_SUCCESS = 'GENDER_SUCCESS'; 
export const GENDER_ERROR = 'GENDER_ERROR';

export const TITLE_SUCCESS = 'TITLE_SUCCESS'; 
export const TITLE_ERROR = 'TITLE_ERROR'; 

export const SECRET_QUESTIONS_SUCCESS = 'SECRET_QUESTIONS_SUCCESS'; 
export const SECRET_QUESTIONS_ERROR = 'SECRET_QUESTIONS_ERROR'; 

export const STATE_SUCCESS = 'STATE_SUCCESS'; 
export const STATE_ERROR = 'STATE_ERROR';

export const INDUSTRY_TYPES_SUCCESS = 'INDUSTRY_TYPES_SUCCESS';
export const INDUSTRY_TYPES_ERROR = 'INDUSTRY_TYPES_ERROR';

export const EMPLOYEE_STATUS_SUCCESS = 'EMPLOYEE_STATUS_SUCCESS';
export const EMPLOYEE_STATUS_ERROR = 'EMPLOYEE_STATUS_ERROR';